apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service-nodeport
  namespace: flask-demo  # 🎯 加上这一行，与应用保持在同一个项目空间
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008  # 访问端口保持 30008 不变
  selector:
    app: flask-hello
    tier: frontend
